version: '3.8'

services:
  # Databases
  # PostgreSQL removed - using remote server at ec2-13-233-106-55.ap-south-1.compute.amazonaws.com:5432

  # MongoDB removed - using local MongoDB installation

  redis:
    image: redis:7-alpine
    container_name: chitchat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chitchat-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: chitchat-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - chitchat-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: chitchat-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - chitchat-network

  # ChitChat Services
  eureka-server:
    build:
      context: .
      dockerfile: chitchat-eureka-server/Dockerfile
    container_name: chitchat-eureka-server
    ports:
      - "8761:8761"
    networks:
      - chitchat-network

  api-gateway:
    build:
      context: .
      dockerfile: chitchat-api-gateway/Dockerfile
    container_name: chitchat-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - chitchat-network

  user-service:
    build:
      context: .
      dockerfile: chitchat-user-service/Dockerfile
    container_name: chitchat-user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - redis
      - kafka
    networks:
      - chitchat-network

  messaging-service:
    build:
      context: .
      dockerfile: chitchat-messaging-service/Dockerfile
    container_name: chitchat-messaging-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - redis
      - kafka
    networks:
      - chitchat-network

  media-service:
    build:
      context: .
      dockerfile: chitchat-media-service/Dockerfile
    container_name: chitchat-media-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - chitchat-network

  calls-service:
    build:
      context: .
      dockerfile: chitchat-calls-service/Dockerfile
    container_name: chitchat-calls-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - redis
      - kafka
    networks:
      - chitchat-network

  notification-service:
    build:
      context: .
      dockerfile: chitchat-notification-service/Dockerfile
    container_name: chitchat-notification-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - kafka
    networks:
      - chitchat-network

  status-service:
    build:
      context: .
      dockerfile: chitchat-status-service/Dockerfile
    container_name: chitchat-status-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - redis
      - kafka
    networks:
      - chitchat-network

  admin-service:
    build:
      context: .
      dockerfile: chitchat-admin-service/Dockerfile
    container_name: chitchat-admin-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - kafka
    networks:
      - chitchat-network

volumes:
  # postgres_data: removed - using remote PostgreSQL
  # mongodb_data: removed - using local MongoDB
  redis_data:

networks:
  chitchat-network:
    driver: bridge
