server:
  port: 9102

spring:
  application:
    name: chitchat-user-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://ec2-65-1-185-194.ap-south-1.compute.amazonaws.com:5432/chitchat
    username: summitcodeworks
    password: 8ivhaah8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuration is now loaded from database via ConfigurationService
# See database/init-postgres.sql for configuration values

jwt:
  secret: ${JWT_SECRET:fallback-secret-key}  # Fallback only
  expiration: ${JWT_EXPIRATION:3600}  # Fallback only

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:}  # Fallback only
  auth:
    token: ${TWILIO_AUTH_TOKEN:}  # Fallback only
  phone:
    number: ${TWILIO_PHONE_NUMBER:}  # Fallback only

firebase:
  project-id: ${FIREBASE_PROJECT_ID:chitchat-9c074}  # Fallback only
  web-api-key: ${FIREBASE_WEB_API_KEY:}  # Fallback only
  auth-domain: ${FIREBASE_AUTH_DOMAIN:chitchat-9c074.firebaseapp.com}  # Fallback only
  storage-bucket: ${FIREBASE_STORAGE_BUCKET:chitchat-9c074.firebasestorage.app}  # Fallback only
  messaging-sender-id: 508577813087
  app-id: 1:508577813087:web:8768669bde9c08b1f5c1ea
  measurement-id: G-6X3E3LRN8Z
  credentials-path: classpath:firebase-service-account.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.chitchat.user: DEBUG
    org.springframework.web: DEBUG
