server:
  port: 9103

spring:
  application:
    name: chitchat-messaging-service
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    mongodb:
      uri: mongodb://summitcodeworks:8ivhaah8@ec2-65-1-185-194.ap-south-1.compute.amazonaws.com:27017/chitchat
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: messaging-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.chitchat.messaging.document,com.chitchat.messaging.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.chitchat.messaging: DEBUG
    org.springframework.web: DEBUG
