server:
  port: 9101

spring:
  application:
    name: chitchat-api-gateway
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      httpclient:
        wiretap: false
      httpserver:
        wiretap: false
      filter:
        json-to-grpc:
          enabled: false
      routes:
        - id: user-service
          uri: lb://CHITCHAT-USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: messaging-service
          uri: lb://CHITCHAT-MESSAGING-SERVICE
          predicates:
            - Path=/api/messages/**
        - id: media-service
          uri: lb://CHITCHAT-MEDIA-SERVICE
          predicates:
            - Path=/api/media/**
        - id: calls-service
          uri: lb://CHITCHAT-CALLS-SERVICE
          predicates:
            - Path=/api/calls/**
        - id: notification-service
          uri: lb://CHITCHAT-NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
        - id: status-service
          uri: lb://CHITCHAT-STATUS-SERVICE
          predicates:
            - Path=/api/status/**
        - id: admin-service
          uri: lb://CHITCHAT-ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 3703ea2161827e52832c162790d1a511e2a7aa22120c34f6d620e703d876697b
  expiration: 3600

firebase:
  project-id: chitchat-9c074
  web-api-key: AIzaSyBefqzOkJgvV0qnmc4Qds43Gi5XvdmAl7g
  auth-domain: chitchat-9c074.firebaseapp.com
  storage-bucket: chitchat-9c074.firebasestorage.app
  messaging-sender-id: 508577813087
  app-id: 1:508577813087:web:8768669bde9c08b1f5c1ea
  measurement-id: G-6X3E3LRN8Z
  credentials-path: classpath:firebase-service-account.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
