server:
  port: 9104

spring:
  application:
    name: chitchat-media-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://ec2-65-1-185-194.ap-south-1.compute.amazonaws.com:5432/chitchat
    username: summitcodeworks
    password: 8ivhaah8
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2      # Reduced for low-resource system
      minimum-idle: 1           # Minimal idle connections
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 300000      # 5 minutes
      max-lifetime: 900000      # 15 minutes
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false             # Disabled to reduce memory and overhead
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false       # Disabled to reduce overhead
        jdbc:
          batch_size: 20        # Optimize batch processing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

aws:
  s3:
    bucket-name: chitchat-media
  region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.chitchat.media: DEBUG
    org.springframework.web: DEBUG
