server:
  port: 9106

spring:
  application:
    name: chitchat-notification-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://ec2-13-233-106-55.ap-south-1.compute.amazonaws.com:5432/chitchat
    username: summitcodeworks
    password: 8ivhaah8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    prefer-ip-address: true

firebase:
  project-id: chitchat-9c074
  web-api-key: AIzaSyBefqzOkJgvV0qnmc4Qds43Gi5XvdmAl7g
  auth-domain: chitchat-9c074.firebaseapp.com
  storage-bucket: chitchat-9c074.firebasestorage.app
  messaging-sender-id: 508577813087
  app-id: 1:508577813087:web:8768669bde9c08b1f5c1ea
  measurement-id: G-6X3E3LRN8Z
  credentials-path: classpath:firebase-service-account.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.chitchat.notification: DEBUG
    org.springframework.web: DEBUG
